



#: Global configs {{{
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g default-shell /bin/zsh
# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"
# Enable RGB colour if running in xterm(1)
set -ga terminal-overrides ",xterm*:Tc"

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane


# Enable the new keyboard protocol for Tmux, and applying to the applications inside it on demand
set -s extended-keys on

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# No bells at all
set -g bell-action none

# Focus events enabled for terminals that support them
set -g focus-events on

#: }}}



#: Global key bindings {{{


# Remap ; to : for convenience
bind \; command-prompt

# Use neovim key bindings
set -g mode-keys vi
set -g status-keys vi

# Increase repeat time for repeatable commands
set -g repeat-time 1000



#bind p paste-buffer       # Paste
#bind C-p choose-buffer    # Tmux clipboard history
#bind "'" delete-buffer\; display "Clipboard history deleted"



#: Window {{{

# Highlight window when it has new activity
setw -g monitor-activity on
set -g visual-activity on

# Start window/pane index at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Re-number windows when one is closed
set -g renumber-windows on




#: Status {{{

# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX}
set status-bg red
%endif

# Refresh `status-left` and `status-right` more often, from every 15s to 5s
set -g status-interval 5

#: }}}



#: Plugins {{{

set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'tmux-plugins/tmux-sensible'

#set -g @plugin "dracula/tmux"
#set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin 'tmux-plugins/tmux-open'

#TMUX_FZF_LAUNCH_KEY="f"
#set -g @plugin 'sainnhe/tmux-fzf'

#set -g @resurrect-strategy-nvim 'session'
#set -g @resurrect-capture-pane-contents 'on'
#set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.config/tmux/plugins/tpm/tpm"

#: }}}
